version: 8.2.2

service:
  type: LoadBalancer
  port: 9201

master:
  replicas: 1
  storage:
    size: 5Gi
    className: local-path

data:
  replicas: 1
  storage:
    size: 50Gi
    className: local-path