config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
  merge:
    accounts:
      A:
        jetstream: enabled
        users:
          - user: a
            password: a
            permissions:
              publish: ["foo", "bar", "help", "$JS.API.>", "_INBOX.>"]
              subscribe: ["foo", "bar", "help", "$JS.API.>", "$JS.EVENT.>", "_INBOX.>"]
      B:
        users:
        - {user: b, password: b}
natsBox:
  contexts:
    a:
      merge: {user: a, password: a}
    b:
      merge: {user: b, password: b}
  defaultContextName: a

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule

# Expose
service:
  merge:
    spec:
      type: LoadBalancer