apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: my
spec:
  image: streamnative/pulsar:2.9.2.15
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
    terminationGracePeriodSeconds: 30
  config:
    custom:
      webSocketServiceEnabled: "true"
    protocolHandlers:
      kop:
        enabled: false
  replicas: 2
  zkServers: my-zk-headless:2181