allowUnsafeConfigurations: true

sharding:
  enabled: false

backup:
  enabled: false

unsafeFlags:
  pxcSize: true
  proxySize: true

pxc:
  size: 1
  volumeSpec:
    pvc:
      resources:
        requests:
          storage: 2Gi
  persistentVolumeClaim:
    storageClassName: local-path

haproxy:
  enabled: true
  size: 1
  resources:
    requests:
      memory: 100Mi

proxysql:
  size: 1
  persistentVolumeClaim:
    storageClassName: local-path

