apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
spec:
  type: LoadBalancer
  selector:
    app: lldap
  ports:
    - name: ldap
      port: 3890
      targetPort: 3890
    - name: web
      port: 17170
      targetPort: 17170