apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - port: 2049
      targetPort: 2049
      protocol: TCP
      name: nfs
    - port: 111
      targetPort: 111
      protocol: TCP
      name: rpcbind
    - port: 20048
      targetPort: 20048
      protocol: TCP
      name: mountd
  selector:
    app: nfs-server
  clusterIP: None # Headless service for stable DNS resolution
