apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: elastic
spec:
  project: tracardi
  source:
    repoURL: 'https://github.com/Tracardi/argocd'
    path: elastic
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic
  syncPolicy:
    syncOptions:
      - CreateNamespace=true