apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starrocks
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: starrocks
spec:
  project: tracardi
  source:
    repoURL: 'https://starrocks.github.io/starrocks-kubernetes-operator'
    targetRevision: 1.8.8
    chart: kube-starrocks
    helm:
      parameters:
        - name: starrocks.starrocksBeSpec.resources.requests.memory
          value: 2Gi
        - name: starrocks.starrocksBeSpec.resources.requests.cpu
          value: '1'
        - name: starrocks.starrocksFESpec.resources.requests.memory
          value: 2Gi
        - name: starrocks.starrocksFESpec.resources.requests.cpu
          value: '1'
        - name: starrocks.starrocksCnSpec.resources.requests.memory
          value: 2Gi
        - name: starrocks.starrocksCnSpec.resources.requests.cpu
          value: '1'
    destination:
      namespace: starrocks
      server: 'https://kubernetes.default.svc'

  syncPolicy:
    syncOptions:
      - CreateNamespace=true