apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starrocks
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: starrocks
spec:
  project: tracardi
  # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
  sources:
    - repoURL: 'https://starrocks.github.io/starrocks-kubernetes-operator'
      targetRevision: 1.8.8
      chart: kube-starrocks
      helm:
        valueFiles:
          - $values/starrocks/local-values.yaml
    - repoURL: 'https://github.com/Tracardi/argocd'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: starrocks

  syncPolicy:
    syncOptions:
      - CreateNamespace=true