apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: pulsar
spec:
  destination:
    namespace: pulsar
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://pulsar.apache.org/charts'
    targetRevision: 3.1.0
    chart: pulsar
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: kube-prometheus-stack.enabled
          value: 'false'
        - name: kube-prometheus-stack.grafana.enabled
          value: 'false'
  project: tracardi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
