apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracardi-ck-worker
  labels:
    app: tracardi-ck-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracardi-ck-worker
  template:
    metadata:
      labels:
        app: tracardi-ck-worker
    spec:
      containers:
        - name: tracardi-ck-worker
          image: tracardi/ck-worker:1.3.x
          env:
            - name: PULSAR_HOST
              value: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
            - name: PULSAR_AUTH_TOKEN
              value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiJ9.lkLZkhoRTS7S11iehntprBA13PjcdDCihanssiSaS0rAHZeJOsCcCKa1XIPZZHbv0SmYwmv4YTIKf7NMSzuI-J0iO9br5caJh_1L3LhUTlsbaWybh7sQPF2rFyEFXa68ojTccjXOk8lWVUg0p3An9q_MMb4jDYND3K89CxRQpwhCPWmF_9Cw4cZJM252NYtSMsVyCkRZsCgu1Zco9GePPlMBrE9MtYpTaIRUuD4MQrunjC9kjWIVgxCEM3wf7B-A8bU_0dDuD5g2WWCsJ_Z-_9T2ucQqglcatrGnsOC0zCmSzmbGDe4372eGo6aak-4kbL3CZ0QnS36Tuji8T1ucHw
            - name: STARROCKS_HOST
              value: "192.168.1.110"
