# Infrastructure

elastic:
  name: es1
  host: cluster-es-http.elastic.svc.cluster.local
  schema: https
  authenticate: true
  port: 9200
  verifyCerts: "no"

redis:
  name: rd1
  host: redis-master.redis.svc.cluster.local
  schema: "redis://"
  authenticate: true
  port: 6379
  db: "0"

pulsar:
  name: ps1
  host: pulsar-proxy.pulsar.svc.cluster.local
#  host: pulsar-std-svc.pulsar-standalone.svc.cluster.local
  schema: "pulsar://"
  authenticate: true
  port: 6650

secrets:
  installationToken: "RISTO"
  dockerHub: "tracardi-dockerhub"
  license:
    licenseKey: "YDDktlIOkXLLLUcDRtuav810bzbKat89Tk+knhsgPrtcrvfpdfp8mL7Py3o9fLu+Sfujb8txPsDhi56v06fDpPYB2RExlZDtYbGH9+km9Yf42LfL/K9I805SR4KUhwMaAaE4zhCHYimJnKJMH1bgKGNQWJ52lDl1P5qHzDiAaspQmxswPAt71jF83tDzz3XF46IPXVvNKXaEMIoHypKhiFbIoSdu3VPUsaHzWV546bijWb21tb9NhqESrKuXBK6Tczm0Vmq9o10vK5avsrMiWDv7AN1Zb6roTHvr4NgnxkJVY9rYpT1rF447Ghp6ColtuhFNce2QCyXgJi7nHr1zd59+yWkOdHQ72pEpRorApg6o2CkPM8vEYK4xCEbc0HY9v5wwBr+zCZFcHWJtawLyoUEZLoEWLxJ5sF029qbLs0Dpy876TtUpK3By5hSXBpmCA41MgaX5UNt/ts83kPX2wNbhnaYOfZi3xGiaXamQMAetpbDonZ0v/fdCx4cFWXIoDx22EVeB0jCnYiaoycVh8yDxfUGnuSmayB0t1XO04JhT3lAsClJSAdwS1Swb/m7y+fW06qW0Y3rYEBcs0VYSWggWDCuTFTtgTTQ49NbU4vjx8RebhVLqPgMAAA==7H749seI7AeDaqdsec2G6U6Cb/9082bS6z7Yf48ceI0Q7yfE6X02dX4Uf5715j9C4254707"
  redis:
    password: "OEFggDSNDZ"
  elastic:
    password: "87p0Fq2M57S3qpI2B6aPKxD1"
  pulsar:
    token: "<PULSAR-TOKEN>"

digitalOcean:
  loadBalancer: true

api:
  test:
    enabled: true

worker:

  flusher:
    profile:
      enabled: false

    session:
      enabled: false


  storage:
    profile:
      enabled: false

    event:
      enabled: false

    session:
      enabled: false


  workflow:
    event:
      enabled: false

  outbound:
    profile:
      enabled: false

    event:
      enabled: false

  internal:
    metrics:
      profile:
        enabled: false

    scheduler:
      event:
        enabled: false

    visitEndScheduler:
      docker:
        enabled: false

    visitEndedDispatcher:
      docker:
        enabled: false

    upgrade:
      docker:
        enabled: false

tms:
  docker:
    enabled: false


segmentationWorker:
  enabled: false


copingWorker:
  enabled: false

