# Infrastructure

elastic:
  name: es1
  host: elastic-std-svc.elastic-standalone.svc.cluster.local
  schema: http
  authenticate: false
  port: 9200
  verifyCerts: "no"

redis:
  name: rd1
  host: redis-std-svc.redis-standalone.svc.cluster.local
  schema: "redis://"
  authenticate: false
  port: 6379
  db: "0"

pulsar:
  name: ps1
  host: pulsar-std-svc.pulsar-standalone.svc.cluster.local
  api: "http://pulsar-std-svc.pulsar-standalone.svc.cluster.local:8080"
  schema: "pulsar://"
  authenticate: false
  port: 6650
  cluster_name: pulsar

mysql:
  name: ms1
  host: percona-db-pxc-db-haproxy.percona.svc.cluster.local
  schema: "mysql+aiomysql://"
  database: "tracardi"
  port: 3306

# Digital ocean

digitalOcean:
  loadBalancer: false
  certId: ""  # SET-CERT-ID


# Definition of defined secrets.

secrets:
  installationToken: "<SET-INSTALLATION-SECRET>"
  dockerHub: "tracardi-dockerhub"
  license:
    licenseKey: "<LICENSE-KEY-VALUE>"
  tms:
    tokenKey: "<SECRET-KEY-VALUE>"
    apiKey: "<API-KEY-VALUE>"
  redis:
    password: "<REDIS-PASSWORD>"
  elastic:
    password: "<ELASTIC-PASSWORD>"
  pulsar:
    token: "<PULSAR-TOKEN>"
  mysql:
    username: "<MYSQL-USER>"
    password: "<MYSQL-PASSWORD>"
  maxmind:
    licenseKey: ""
    accountId: ""
  mergingToken: "1180015e-38d0-4eb7-8017-40e6a7937659"


# General Tracardi configuration. Version, images, multi-tenancy, etc.

config:
  multiTenant:
    multi: "no"
  storage:
    failOver:
      enabled: true
      size: 1Gi
  primaryId: "emm-"  # This value should be set only once during installation and never changed

api:
  image:
    repository: tracardi/com-tracardi-api
    pullPolicy: IfNotPresent
    tag: 0.9.0-rc3  # Tag should be the same for gui and backend
  test:
    enabled: true
    replicas: 1
    config:
      saveLogs: "yes"
      loggingLevel: "INFO"
      apiDocs: "yes"
      asyncProcessing: "yes"
      enableWorkflow: "yes"
      enableEventDestinations: "yes"
      enableProfileDestinations: "yes"
      enableIdentification: "yes"
      enablePostEventSegmentation: "yes"
      enableProfileFlush: "yes"
      eventPartitioning: "month"
      profilePartitioning: "quarter"
      sessionPartitioning: "quarter"
    storage:
      failOver:
        enabled: true
        size: 1Gi
    service:
      port: 8686

  production:
    enabled: true
    replicas: 1
    config:
      saveLogs: "yes"
      loggingLevel: "INFO"
      apiDocs: "no"
      asyncProcessing: "yes"
      enableWorkflow: "yes"
      enableEventDestinations: "yes"
      enableProfileDestinations: "yes"
      enableIdentification: "yes"
      enablePostEventSegmentation: "yes"
      enableProfileFlush: "yes"
      elasticSavePool: 0
      eventPartitioning: "month"
      profilePartitioning: "quarter"
      sessionPartitioning: "quarter"
    storage:
      failOver:
        enabled: true
        size: 1Gi
    service:
      port: 8585

gui:
  image:
    repository: tracardi/tracardi-gui
    pullPolicy: IfNotPresent
    tag: 0.9.0-rc3  # Tag should be the same for gui and backend
  console:
    enabled: true
    replicas: 1
    service:
        port: 8787
    config:
      mode: "with-deployment"

tms:
  image:
    repository: tracardi/tms
    pullPolicy: IfNotPresent
    tag: 0.9.0-rc3  # Tag should be the same for gui and backend
  docker:
    enabled: true
    replicas: 1
    config:
      loggingLevel: "INFO"
    service:
      port: 8383
      name: be-fa-tms-svc  # The name of tms service

# TODO Jobs to be removed
job:
  metrics:
    image:
      repository: tracardi/com-metrics-job
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    docker:
      enabled: false
      config:
        successfulJobsHistoryLimit: 2
        failedJobsHistoryLimit: 2
        schedules:
          - name: jb-metrics # every 30min get last events of last month and skip first 20 minutes.
            schedule: "*/30 * * * *"

  segmentation:
    conditional:
      image:
        repository: tracardi/com-cond-segmentation-job
        tag: 0.9.0-rc3
        pullPolicy: IfNotPresent
      docker:
        enabled: false
        config:
          loggingLevel: "INFO"
          successfulJobsHistoryLimit: 2
          failedJobsHistoryLimit: 2
          schedules:
            - name: jb-segmentation-conditional
              schedule: "*/10 * * * *"
    workflow:
      image:
        repository: tracardi/com-wf-segmentation-job
        tag: 0.9.0-rc3
        pullPolicy: IfNotPresent
      docker:
        enabled: false
        config:
          loggingLevel: "INFO"
          successfulJobsHistoryLimit: 2
          failedJobsHistoryLimit: 2
          schedules:
            - name: jb-segmentation-workflow
              schedule: "*/15 * * * *"

worker:
  apm:
    image:
      repository: tracardi/apm
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    profile:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"

  activation:
    image:
      repository: tracardi/com-tracardi-activation-worker
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    profile:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"

  flusher:
    image:
      repository: tracardi/com-tracardi-flusher-worker
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    profile:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"
    session:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"

  storage:
    image:
      repository: tracardi/com-tracardi-storage-worker
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    profile:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"
    event:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"
    session:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"

  workflow:
    image:
      repository: tracardi/com-tracardi-workflow-worker
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    event:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"

  outbound:
    image:
      repository: tracardi/com-tracardi-outbound-worker
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    profile:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"
    event:
      enabled: true
      replicas: 1
      config:
        loggingLevel: "INFO"

  internal:
    metrics:
      image:
        repository: tracardi/com-tracardi-metrics-worker
        tag: 0.9.0-rc3
        pullPolicy: IfNotPresent
      profile:
        enabled: true
        replicas: 1
        config:
          loggingLevel: "INFO"
    scheduler:
      image:
        repository: tracardi/com-tracardi-scheduler-worker
        tag: 0.9.0-rc3
        pullPolicy: IfNotPresent
      event:
        enabled: true
        replicas: 1
        config:
          loggingLevel: "INFO"
    visitEndScheduler:
      image:
        repository: tracardi/com-tracardi-visit-end-checker-worker
        tag: 0.9.0-rc3
        pullPolicy: IfNotPresent
      docker:
        enabled: true
        replicas: 1
        config:
          loggingLevel: "INFO"
          defaultReschedulingTime: 1200  # 20 min
          closeVisitAfter: 2100  # 35 min
    visitEndedDispatcher:
      image:
        repository: tracardi/com-tracardi-visit-ended-worker
        tag: 0.9.0-rc3
        pullPolicy: IfNotPresent
      docker:
        enabled: true
        replicas: 1
        config:
          loggingLevel: "INFO"
    upgrade:
      image:
        repository: tracardi/update-worker
        tag: 0.9.0-rc3
        pullPolicy: IfNotPresent
      docker:
        enabled: true
        replicas: 1
        config:
          saveLogs: "no"
          loggingLevel: "INFO"
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
#    trigger:
#      image:
#        repository: tracardi/com-tracardi-trigger-worker
#        tag: 0.9.0-rc3
#        pullPolicy: IfNotPresent
#      segmentation:
#        enabled: false
#        replicas: 1
#        config:
#          loggingLevel: "INFO"

# Bridges. Services responsible for collection data from different channels. They bridge the defined transportation protocol to tracardi event source.

bridge:
  queue:
    image:
      repository: tracardi/com-bridge-queue
      tag: 0.9.0-rc3
      pullPolicy: IfNotPresent
    docker:
      enabled: false
      replicas: 1
      config:
        loggingLevel: "INFO"

# -----------------------------------------

segmentationWorker:
  enabled: true
  image:
    repository: tracardi/com-tracardi-segmentation-worker
    tag: 0.9.0-rc3
    pullPolicy: IfNotPresent
  config:
    saveLogs: "no"
    loggingLevel: "INFO"

copingWorker:
  enabled: true
  image:
    repository: tracardi/com-tracardi-coping-worker
    tag: 0.9.0-rc3
    pullPolicy: IfNotPresent
  config:
    saveLogs: "no"
    loggingLevel: "INFO"
