{{ if and .Values.secrets.dockerHub .Values.bridge.queue.docker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-queue-prod
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "bg-queue-prod") | nindent 4 }}
spec:
  replicas: {{ .Values.bridge.queue.docker.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "bg-queue-prod") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "bg-queue-prod") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub | quote }}
      containers:
      - name: bg-queue-prod
        image: "{{ .Values.bridge.queue.image.repository }}:{{ .Values.bridge.queue.image.tag }}"
        imagePullPolicy: {{ .Values.bridge.queue.image.pullPolicy }}
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 80Mi
            cpu: 300m
        env:
          {{- include "tracardi.env" (dict "ctx" .) | nindent 10 }}
          - name: LOGGING_LEVEL
            value: {{ .Values.bridge.queue.docker.config.loggingLevel | quote }}
          - name: PRODUCTION
            value: "yes"
          - name: BRIDGE_CHECK
            value: "1800"

        volumeMounts:
          - name: pre-resources-vol
            mountPath: "/system/com_tracardi/storage/preconfig/data/resources.json"
            subPath: "resources.json"
          - name: pre-destinations-vol
            mountPath: "/system/com_tracardi/storage/preconfig/data/destinations.json"
            subPath: "destinations.json"
          - name: pre-event-sources-vol
            mountPath: "/system/com_tracardi/storage/preconfig/data/event-sources.json"
            subPath: "event-sources.json"
          - name: tenant-aliases-vol
            mountPath: "/system/com_tracardi/storage/preconfig/data/tenant-aliases.json"
            subPath: "tenant-aliases.json"

      volumes:
        - name: pre-resources-vol
          configMap:
            name: pre-resources-cm

        - name: pre-destinations-vol
          configMap:
            name: pre-destinations-cm

        - name: pre-event-sources-vol
          configMap:
            name: pre-event-sources-cm

        - name: tenant-aliases-vol
          configMap:
            name: tenant-aliases-cm
{{ end }}