{{ if and .Values.secrets.dockerHub .Values.job.obs_end.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-obs-end
  labels:
    app: job-obs-end
    version: {{ .Chart.AppVersion | quote }}
    {{- include "airembr.labels" (dict "ctx" . "component" "job-obs-end") | nindent 4 }}
spec:
  schedule: "*/30 * * * *" # every 30 minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            {{- include "airembr.podLabels" (dict "ctx" . "component" "job-obs-end") | nindent 12 }}
        spec:
          {{- include "chart.nodeAffinity" (dict "context" . "path" "job.obs_end") | nindent 10 }}
          {{ if .Values.job.obs_end.spread }}
            {{range .Values.job.obs_end.spread }}
              {{ toYaml . | nindent 10 }}
            {{ end }}
          {{ end }}
          imagePullSecrets:
            - name: {{ .Values.secrets.dockerHub | quote }}
          restartPolicy: OnFailure
          containers:
            - name: job-obs-end
              image: "{{ .Values.job.obs_end.image.repository }}:{{ .Values.job.obs_end.image.tag }}"
              imagePullPolicy: {{ .Values.job.obs_end.image.pullPolicy }}
              resources:
                limits:
                  memory: {{ .Values.job.obs_end.resources.limits.memory }}
                  cpu: {{ .Values.job.obs_end.resources.limits.cpu }}
                requests:
                  memory: {{ .Values.job.obs_end.resources.requests.memory }}
                  cpu: {{ .Values.job.obs_end.resources.requests.cpu }}
              env:
                {{- include "airembr.env" (dict "ctx" .) | nindent 16 }}
                - name: LOGGING_LEVEL
                  value: {{ .Values.job.obs_end.config.loggingLevel | quote }}
                - name: STATE_STORE
                  value: "mysql"
{{ end }}
