{{ if and .Values.worker.upgrade.docker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wk-rd-upgrades
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "wk-rd-upgrades") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.upgrade.docker.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "wk-rd-upgrades") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "wk-rd-upgrades") | nindent 8 }}
    spec:
      containers:
        - name: wk-rd-upgrades
          image: "{{ .Values.worker.upgrade.image.repository }}:{{ .Values.worker.upgrade.image.tag }}"
          imagePullPolicy: {{ .Values.worker.upgrade.image.pullPolicy }}
          resources:
            limits:
              memory: {{ .Values.worker.upgrade.docker.resources.limits.memory }}
              cpu: {{ .Values.worker.upgrade.docker.resources.limits.cpu }}
            requests:
              memory: 100Mi
              cpu: 300m
          env:
            {{- include "tracardi.env" (dict "ctx" . "nolicense" "true") | nindent 12 }}
            - name: LOGGING_LEVEL
              value: {{ .Values.worker.upgrade.docker.config.loggingLevel | quote }}
{{ end }}