{{ if and .Values.secrets.dockerHub .Values.api.private.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: be-fa-private
  labels:
    app: be-fa-private
    version: {{ .Chart.AppVersion | quote }}
    {{- include "tracardi.labels" (dict "ctx" . "component" "be-fa-private") | nindent 4 }}
spec:
  serviceName: "tracardi-api-private"
  replicas: {{ .Values.api.private.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
{{ if .Values.config.storage.failOver.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: fail-over-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.config.storage.failOver.size }}
{{end}}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "be-fa-private") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub  | quote }}
      initContainers:
        - name: tracardi-init
          image: tracardi/init:{{ .Values.api.image.tag }}
          imagePullPolicy: Always
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: LOGGING_LEVEL
              value: debug
      containers:
        - name: be-fa-private
          {{- include "tracardi.image" (dict "ctx" . "repo" .Values.api.image.repository "tag" .Values.api.image.tag "policy" .Values.api.image.pullPolicy) | nindent 10 }}
          resources:
            limits:
              memory: 250Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 100m
          ports:
            - name: private-port
              containerPort: 80
{{ if not .Values.config.multiTenant }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 60
{{ end }}
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: DEMO
              value: {{ .Values.config.demo | quote }}
            - name: EXPOSE_GUI_API
              value: "yes"
            - name: PRODUCTION
              value: "no"
            - name: LOGGING_LEVEL
              value: {{ .Values.api.private.config.loggingLevel | quote }}
            - name: API_DOCS
              value: {{ .Values.api.private.config.apiDocs | quote}}
            - name: SAVE_LOGS
              value: {{ .Values.api.private.config.saveLogs | quote }}
            - name: ENABLE_EVENT_DESTINATIONS
              value: {{ .Values.api.private.config.enableEventDestinations | quote }}
            - name: ENABLE_PROFILE_DESTINATIONS
              value: {{ .Values.api.private.config.enableProfileDestinations | quote }}
            - name: ENABLE_WORKFLOW
              value: {{ .Values.api.private.config.enableWorkflow | quote }}
            - name: ENABLE_IDENTIFICATION_POINT
              value: {{ .Values.api.private.config.enableIdentification | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}

{{ if .Values.config.storage.failOver.enabled }}
          volumeMounts:
            - mountPath: "/opt/tracardi"
              name: fail-over-storage
{{end}}
---
apiVersion: v1
kind: Service
metadata:
  name: be-fa-private-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.private.service.port }}
      targetPort: private-port

{{ if .Values.digitalOcean.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: do-be-fa-private-lb
  {{ if .Values.digitalOcean.certId }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.digitalOcean.certId | quote }}
  {{ end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
  ports:
    - name: http-{{ .Values.api.private.service.port }}
      protocol: TCP
      port: {{ .Values.api.private.service.port }}
      targetPort: private-port
{{ if .Values.digitalOcean.certId }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: private-port
{{ end }}

{{ end }}
{{ end }}


