{{ if and .Values.secrets.dockerHub .Values.api.private.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-fa-private
  labels:
    app: be-fa-private
    version: {{ .Chart.AppVersion | quote }}
    {{- include "tracardi.labels" (dict "ctx" . "component" "be-fa-private") | nindent 4 }}
spec:
  replicas: {{ .Values.api.private.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "be-fa-private") | nindent 8 }}
    spec:
      {{- include "chart.nodeAffinity" (dict "context" . "path" "api.private") | nindent 6 }}
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub  | quote }}
      initContainers:
        - name: tracardi-init
          image: tracardi/init:{{ .Values.api.image.tag }}
          imagePullPolicy: Always
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: LOGGING_LEVEL
              value: debug
      containers:
        - name: be-fa-private
          {{- include "tracardi.image" (dict "ctx" . "repo" .Values.api.image.repository "tag" .Values.api.image.tag "policy" .Values.api.image.pullPolicy) | nindent 10 }}
          resources:
            limits:
              memory: {{ .Values.api.private.resources.limits.memory }}
              cpu: {{ .Values.api.private.resources.limits.cpu }}
            requests:
              memory: {{ .Values.api.private.resources.requests.memory }}
              cpu: {{ .Values.api.private.resources.requests.cpu }}
          ports:
            - name: private-port
              containerPort: 80
          {{- include "tracardi.livenessProbe" . | nindent 10 }}
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: DEMO
              value: {{ .Values.config.demo | quote }}
            - name: EXPOSE_GUI_API
              value: {{ .Values.api.private.config.enableGuiApi | quote }}
            - name: PRODUCTION
              value: "no"
            - name: LOGGING_LEVEL
              value: {{ .Values.api.private.config.loggingLevel | quote }}
            - name: API_DOCS
              value: {{ .Values.api.private.config.apiDocs | quote}}
            - name: SAVE_LOGS
              value: {{ .Values.api.private.config.saveLogs | quote }}
            - name: SERVER_LOGGING_LEVEL
              value: {{ .Values.api.private.config.serverLoggingLevel | quote }}
            - name: ELASTIC_LOGGING_LEVEL
              value: {{ .Values.api.private.config.elasticloggingLevel | quote }}

          volumeMounts:
            {{- include "tracardi.volumeMounts" (dict "ctx" .) | nindent 12 }}

      volumes:
        {{- include "tracardi.volumes" (dict "ctx" .) | nindent 8 }}

{{ end }}


