{{ if and .Values.secrets.dockerHub .Values.api.public.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-fa-public
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "be-fa-public") | nindent 4 }}
spec:
  replicas: {{ .Values.api.public.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-public") | nindent 6 }}
{{ if .Values.config.storage.failOver.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: fail-over-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.config.storage.failOver.size }}
{{end}}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "be-fa-public") | nindent 8 }}
    spec:
      {{- include "chart.nodeAffinity" (dict "context" . "path" "api.public") | nindent 6 }}
      {{ if .Values.api.public.spread }}
        {{range .Values.api.public.spread }}
          {{ toYaml . | nindent 6 }}
        {{ end }}
      {{ end }}
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub | quote }}
      initContainers:
        - name: tracardi-init
          image: tracardi/init:{{ .Values.api.image.tag }}
          imagePullPolicy: Always
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: LOGGING_LEVEL
              value: debug
      containers:
        - name: be-fa-public
          {{- include "tracardi.image" (dict "ctx" . "repo" .Values.api.image.repository "tag" .Values.api.image.tag "policy" .Values.api.image.pullPolicy) | nindent 10 }}
          resources:
            limits:
              memory: {{ .Values.api.public.resources.limits.memory }}
              cpu: {{ .Values.api.public.resources.limits.cpu }}
            requests:
              memory: {{ .Values.api.public.resources.requests.memory }}
              cpu: {{ .Values.api.public.resources.requests.cpu }}
          ports:
            - name: be-fa-p-port
              containerPort: 80
{{ if not .Values.config.multiTenant }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 60
{{ end }}
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: EXPOSE_GUI_API
              value: "no"
            - name: PRODUCTION
              value: "yes"
            - name: LOGGING_LEVEL
              value: {{ .Values.api.public.config.loggingLevel | quote }}
            - name: SAVE_LOGS
              value: {{ .Values.api.public.config.saveLogs | quote }}

          volumeMounts:
            - name: pre-resources-vol
              mountPath: "/system/com_tracardi/storage/preconfig/data/resources.json"
              subPath: "resources.json"
            - name: pre-destinations-vol
              mountPath: "/system/com_tracardi/storage/preconfig/data/destinations.json"
              subPath: "destinations.json"
            - name: pre-event-sources-vol
              mountPath: "/system/com_tracardi/storage/preconfig/data/event-sources.json"
              subPath: "event-sources.json"
            - name: tenant-aliases-vol
              mountPath: "/system/com_tracardi/storage/preconfig/data/tenant-aliases.json"
              subPath: "tenant-aliases.json"

      volumes:
        - name: pre-resources-vol
          configMap:
            name: pre-resources-cm

        - name: pre-destinations-vol
          configMap:
            name: pre-destinations-cm

        - name: pre-event-sources-vol
          configMap:
            name: pre-event-sources-cm

        - name: tenant-aliases-vol
          configMap:
            name: tenant-aliases-cm


{{ end }}