{{ if and .Values.tms.docker.enabled (eq .Values.config.multiTenant.multi "yes") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-fa-tms
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "be-fa-tms") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-tms") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "be-fa-tms") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub  | quote }}
      containers:
        - name: be-fa-tms
          {{- include "tracardi.image" (dict "ctx" . "repo" .Values.tms.image.repository "tag" .Values.tms.image.tag "policy" .Values.tms.image.pullPolicy) | nindent 10 }}
          ports:
            - containerPort: 80
              name: tms-port
          env:
            {{- include "tracardi.env" (dict "ctx" .) | nindent 12 }}
            - name: LOGGING_LEVEL
              value: {{ .Values.tms.docker.config.loggingLevel | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.tmsApi.database }}
{{ if and .Values.secrets.tms.apiKey }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: "tms"
                  key: "api-key"
{{ else if and .Values.secrets.tms.valueFrom.apiKey.name .cValues.secrets.tms.valueFrom.apiKey.key }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tms.valueFrom.apiKey.name | quote }}
                  key: {{ .Values.secrets.tms.valueFrom.apiKey.key | quote }}
{{ end }}
{{ if and .Values.secrets.tms.secretKey }}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: "tms"
                  key: "secret-key"
{{ else if and .Values.secrets.tms.valueFrom.secretKey.name .cValues.secrets.tms.valueFrom.secretKey.key }}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tms.valueFrom.secretKey.name | quote }}
                  key: {{ .Values.secrets.tms.valueFrom.secretKey.key | quote }}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tms.docker.service.name }}
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-tms") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.tms.docker.service.port }}
      targetPort: tms-port

{{ if .Values.digitalOcean.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: do-be-fa-tms-lb
  {{ if .Values.digitalOcean.certId }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.digitalOcean.certId | quote }}
  {{ end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-tms") | nindent 6 }}
  ports:
    - name: http-{{ .Values.tms.docker.service.port }}
      protocol: TCP
      port: {{ .Values.tms.docker.service.port }}
      targetPort: tms-port
    {{ if .Values.digitalOcean.certId }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: tms-port
    {{ end }}

{{ end }}
{{ end }}