apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.name }}
spec:
  version: {{ .Values.version }}
  http:
    service:
      spec:
        type: {{ .Values.service.type }}  # default ClusterIP
        ports:
          - name: https
            protocol: TCP
            port: {{ .Values.service.port }}
  nodeSets:
  - name: master
    count: {{ .Values.master.replicas }}
    config:
      node.roles: [ "master" ]
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.master.storage.size }}
    podTemplate:
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]

  - name: data
    count: {{ .Values.data.replicas }}
    config:
      node.roles: [ "data" ]
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.data.storage.size }}
    podTemplate:
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]

#  - name: transform-node
#    count: 1
#    config:
#      node.roles: [ "transform" ]
#    volumeClaimTemplates:
#      - metadata:
#          name: elasticsearch-data
#        spec:
#          accessModes:
#            - ReadWriteOnce
#          resources:
#            requests:
#              storage: 50Gi
#    podTemplate:
#      spec:
#        initContainers:
#          - name: sysctl
#            securityContext:
#              privileged: true
#              runAsUser: 0
#            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
