apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airembr-collector
  namespace: monitoring
  labels:
    release: prometheus   # MUST match Helm release name
spec:
  namespaceSelector:
    matchNames:
      - airembr
  selector:
    matchLabels:
      app: airembr-collector
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
