image:
  pullPolicy: IfNotPresent
  repository: registry.rocket.chat/rocketchat/rocket.chat
  tag: 6.9.3

mongodb:
  enabled: true  #For test purposes, a single mongodb pod is deployed, consider an external MongoDB cluster for production environments
  auth:
    passwords:
      - rocketchat
    rootPassword: rocketchatroot

microservices:
  enabled: false  #This must be set to false for a monolithic deployment
host: community.tracardi.com
ingress:
  enabled: false
  ingressClassName: nginx  # State the ingress controller that is installed in the K8s cluster
  annotations:
    cert-manager.io/cluster-issuer: production-cert-issuer # Replace with the name of your ClusterIssuer
  tls:
    - secretName: rckube #This is the name of the secret - You can use a different name if needed
      hosts:
        - community.tracardi.com #This is the domain for your Rocket.Chat server, Replace it with your own domain