{{ if and .Values.secrets.elastic.password .Values.secrets.elastic.username }}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret
type: Opaque
data:
  elastic-username: {{ .Values.secrets.elastic.username | b64enc }}
  elastic-password: {{ .Values.secrets.elastic.password | b64enc }}
{{ end }}
