{{ if and .Values.secrets.mysql.password .Values.secrets.mysql.username }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-username: {{ .Values.secrets.mysql.username | b64enc }}
  mysql-password: {{ .Values.secrets.mysql.password | b64enc }}
{{ end }}