{{ if and .Values.secrets.tms.secretKey .Values.secrets.tms.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: tms
type: Opaque
data:
  secret-key: {{ .Values.secrets.tms.secretKey | b64enc }}
  api-key: {{ .Values.secrets.tms.apiKey | b64enc }}
{{ end }}