{{ if and .Values.secrets.tms.tokenKey .Values.secrets.tms.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: tms
type: Opaque
data:
  token-key: {{ .Values.secrets.tms.tokenKey | b64enc }}
  api-key: {{ .Values.secrets.tms.apiKey | b64enc }}
{{ end }}