{{ if and .Values.secrets.license.licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: tracardi-license
type: Opaque
data:
  license-key: {{ .Values.secrets.license.licenseKey | b64enc }}
{{ end }}