apiVersion: v1
kind: Namespace
metadata:
  name: operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-eck
  namespace: operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable
  name: elastic-cloud-eck
  source: operatorhubio-catalog
  sourceNamespace: olm

---
apiVersion: operators.coreos.com/v1alpha2 # (2)
kind: OperatorGroup
metadata:
  name: elasticsearch-eck
  namespace: operators
  annotations:
    argocd.argoproj.io/sync-wave: "2" # (3)
spec: {}


