# Infrastructure

redis:
  host: redis-master.redis.svc.cluster.local
  db: "1"

kafka:
  # Identifier for Kafka service instance
  name: kafka1
  # Host address for Kafka
  servers: 192.168.1.119:9092,192.168.1.119:9093,192.168.1.119:9094
  # Enable or disable authentication for Kafka
  security_protocol: "SASL_PLAINTEXT"
  sasl:
    mechanism: "SCRAM-SHA-512"

  # Enable kafka service
  enabled: true

mysql:
  host: 192.168.1.28


secrets:
  dockerHub: "airembr-dockerhub"

  pulsar:
    token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiJ9.lkLZkhoRTS7S11iehntprBA13PjcdDCihanssiSaS0rAHZeJOsCcCKa1XIPZZHbv0SmYwmv4YTIKf7NMSzuI-J0iO9br5caJh_1L3LhUTlsbaWybh7sQPF2rFyEFXa68ojTccjXOk8lWVUg0p3An9q_MMb4jDYND3K89CxRQpwhCPWmF_9Cw4cZJM252NYtSMsVyCkRZsCgu1Zco9GePPlMBrE9MtYpTaIRUuD4MQrunjC9kjWIVgxCEM3wf7B-A8bU_0dDuD5g2WWCsJ_Z-_9T2ucQqglcatrGnsOC0zCmSzmbGDe4372eGo6aak-4kbL3CZ0QnS36Tuji8T1ucHw"
    enabled: false

  kafka:
    sasl_plain_username: "admin"
    sasl_plain_password: "supersecret"
    enabled: true

  redis:
    password: "D7RhiWgZvD"

  mysql:
    username: "root"
    password: "lYJ!)%So<Gn,=XC)vT9"

  starrocks:
    username: "root"
    password: "3BoZGE68bC2D"

api:
  collector:
    image:
      pullPolicy: Always
    config:
      loggingLevel: "dev_info"
  gui:
    image:
      pullPolicy: Always

gui:
  image:
    pullPolicy: Always

worker:

  collector:
    image:
      pullPolicy: Always
    config:
      loggingLevel: "dev_info"

  background:
    image:
      pullPolicy: Always
    config:
      loggingLevel: "dev_info"
    resources:
      limits:
        memory: 1000Mi # 400Mi max for worker that saves data only, not collector
        cpu: 1000m  # 700m max for worker that saves data only, not collector
      requests:
        memory: 300Mi
        cpu: 300m

  attachment:
    enabled: false

  trigger:
    enabled: false

job:
  imap:
    enabled: false
    image:
      pullPolicy: Always

  ical:
    enabled: false
    image:
      pullPolicy: Always

  timer:
    enabled: false
    image:
      pullPolicy: Always

  obs_end:
    enabled: false
    image:
      pullPolicy: Always

  event_attach:
    enabled: false
    image:
      pullPolicy: Always


ext:
  embedding:
    hf384:
      enabled: false
      image:
        pullPolicy: Always
      config:
        loggingLevel: "info"
        serverLoggingLevel: "info"
        apiKey: "some-random-value"