#
# This is the deployment for MtSilesia Bridge
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-bridge
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-bridge
  template:
    metadata:
      labels:
        app: mt-bridge
        tier: backend
    spec:
      containers:
      - name: mt-bridge
        image: {{ .Values.bridge.image }}
        imagePullPolicy: Always
        env:
          - name: INSTALLATION_TOKEN
            value: "RISTO"
          - name: SYSTEM_EVENTS
            value: "no"
          - name: BRIDGE_ID
            value: {{ .Values.bridge.id }}
          - name: API_DOCS
            value: "no"
          - name: ELASTIC_SCHEME
            value: {{ .Values.elastic.schema | quote }}
          - name: ELASTIC_HOST
            value: {{ .Values.elastic.host | quote}}
          - name: ELASTIC_HTTP_AUTH_USERNAME
            value: {{ .Values.secrets.elastic.username | quote}}
          - name: ELASTIC_HTTP_AUTH_PASSWORD
            value: {{ .Values.secrets.elastic.password | quote}}
          - name: ELASTIC_PORT
            value: {{ .Values.elastic.port | quote }}
          - name: ELASTIC_VERIFY_CERTS
            value: {{ .Values.elastic.verifyCerts | quote }}

          - name: REDIS_HOST
            value: {{ .Values.redis.host | quote }}
          - name: REDIS_PASSWORD
            value: {{ .Values.secrets.redis.password | quote }}

          - name: MYSQL_HOST
            value: {{ .Values.mysql.host | quote}}
          - name: MYSQL_USERNAME
            value: {{ .Values.secrets.mysql.username | quote}}
          - name: MYSQL_PASSWORD
            value: {{ .Values.secrets.mysql.password | quote }}
          - name: MYSQL_PORT
            value: {{ .Values.mysql.port | quote }}
          - name: MYSQL_SCHEMA
            value: "mysql+aiomysql://"

          - name: PULSAR_DISABLED
            value: "yes"

          - name: ENABLE_PROFILE_DESTINATIONS
            value: "no"
          - name: ENABLE_FIELD_UPDATE_LOG
            value: "no"
          - name: AUTO_PROFILE_MERGING
            value: "no"

---
apiVersion: v1
kind: Service
metadata:
  name: mt-bridge-svc
spec:
  type: LoadBalancer
  selector:
    app: mt-bridge
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
