{{ if and .Values.gui.console.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-config
data:
  custom.js: |
    export const custom = {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-rj-gui
  labels:
    {{- include "tracardi.labels" (dict "ctx" . "component" "fe-rj-gui") | nindent 4 }}
spec:
  replicas: {{ .Values.gui.console.replicas }}
  selector:
    matchLabels:
      {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "fe-rj-gui") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tracardi.podLabels" (dict "ctx" . "component" "fe-rj-gui") | nindent 8 }}
    spec:
      {{- include "chart.nodeAffinity" (dict "context" . "path" "gui") | nindent 6 }}
      imagePullSecrets:
        - name: {{ .Values.secrets.dockerHub | quote }}
      containers:
        - name: fe-rj-gui
          {{- include "tracardi.image" (dict "ctx" . "repo" .Values.gui.image.repository "tag" .Values.gui.image.tag "policy" .Values.gui.image.pullPolicy) | nindent 10 }}
          resources:
            limits:
              memory: 50Mi
              cpu: 500m
            requests:
              memory: 20Mi
              cpu: 300m
          env:
            - name: MODE
              value: {{ .Values.gui.console.config.mode | quote }}
            - name: MULTI_TENANT
              value: {{ .Values.config.multiTenant.multi | quote }}
            - name: ALLOW_UPDATES_ON_PRODUCTION
              value: {{ .Values.gui.console.config.allowUpdatesOnProduction | quote }}
          ports:
            - containerPort: 80
              name: gui-port
          volumeMounts:
            - name: gui-config-volume
              mountPath: /usr/share/nginx/html/config
      volumes:
        - name: gui-config-volume
          configMap:
            name: gui-config

{{ end }}