{{ if and .Values.secrets.kafka.sasl_plain_password .Values.secrets.kafka.sasl_plain_username }}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  kafka_sasl_username: {{ .Values.secrets.kafka.sasl_plain_username | b64enc }}
  kafka_sasl_password: {{ .Values.secrets.kafka.sasl_plain_password | b64enc }}
{{ end }}
