{{ if and .Values.secrets.kafka.sasl_plain_password }}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  kafka_sasl_password: {{ .Values.secrets.kafka.sasl_plain_password | b64enc }}
{{ end }}
