{{ if and .Values.secrets.kafka.sasl_plain_password }}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-password
type: Opaque
data:
  kafka_sasl_password: {{ .Values.secrets.kafka.sasl_plain_password | b64enc }}
{{ end }}

{{ if and .Values.secrets.kafka.sasl_plain_username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-username
type: Opaque
data:
  kafka_sasl_username: {{ .Values.secrets.kafka.sasl_plain_username | b64enc }}
{{ end }}
