{{ if and .Values.secrets.starrocks.password .Values.secrets.starrocks.username }}
apiVersion: v1
kind: Secret
metadata:
  name: starrocks-secret
type: Opaque
data:
  starrocks_username: {{ .Values.secrets.starrocks.username | b64enc }}
  starrocks_password: {{ .Values.secrets.starrocks.password | b64enc }}
{{ end }}
