apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  ingressClassName: traefik
  rules:
    - host: minio.sophierc.com  # Change to your domain
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: minio-console  
              port:
                number: 9090  # MinIO default API port (HTTPS unsigned cert)
        - path: /console
          pathType: Prefix
          backend:
            service:
              name: minio-hl
              port:
                number: 9000  # MinIO default API port
  tls:
    - hosts:
        - minio.sophierc.com
