starrocks:
  starrocksBeSpec:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: 1
  starrocksFESpec:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: 1
  starrocksCnSpec:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 1