starrocks:
  initPassword:
    enabled: true
    password: "root"
  starrocksBeSpec:
    replicas: 1
    storageSpec:
      name: sr-be-storage
      # fe container stop running if the disk free space which the fe meta directory residents, is less than 5Gi.
      logStorageSize: 10Gi
      storageSize: 10Gi
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
  starrocksFESpec:
    replicas: 1
    storageSpec:
      name: sr-fe-storage
      # fe container stop running if the disk free space which the fe meta directory residents, is less than 5Gi.
      logStorageSize: 10Gi
      storageSize: 10Gi
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
    service:
      type: LoadBalancer  # Comment out to disable
  starrocksCnSpec:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 1