starrocks:
  initPassword:
    enabled: true
    password: "3BoZGE68bC2D"
  starrocksBeSpec:
    replicas: 3
    repository: starrocks/fe-ubuntu
    tag: 3.3-latest
    storageSpec:
      name: starrocks-be-storage
      # fe container stop running if the disk free space which the fe meta directory residents, is less than 5Gi.
      logStorageSize: 10Gi
      storageSize: 10Gi
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 1
        memory: 1Gi
  starrocksFESpec:
    replicas: 1
    image:
      repository: starrocks/fe-ubuntu
      tag: 3.3-latest
    storageSpec:
      name: starrocks-fe-storage
      # fe container stop running if the disk free space which the fe meta directory residents, is less than 5Gi.
      logStorageSize: 10Gi
      storageSize: 10Gi
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 1
        memory: 1Gi
    service:
      type: LoadBalancer  # Comment out to disable
  starrocksCnSpec:
    replicas: 1
    repository: starrocks/fe-ubuntu
    tag: 3.3-latest
    resources:
      requests:
        memory: 1Gi
        cpu: 1