apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
  namespace: dex
data:
  config.yaml: |
    issuer: http://<NODE-IP>:30556

    storage:
      type: memory

    web:
      http: 0.0.0.0:5556

    connectors:
      - type: ldap
        id: ldap
        name: LLDAP
        config:
          host: lldap.lldap.svc.cluster.local:3890
          insecureNoSSL: true

          bindDN: uid=admin,ou=people,dc=example,dc=local
          bindPW: admin12345

          userSearch:
            baseDN: ou=people,dc=example,dc=local
            filter: "(objectClass=inetOrgPerson)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: cn

          groupSearch:
            baseDN: ou=groups,dc=example,dc=local
            filter: "(objectClass=groupOfNames)"
            userAttr: DN
            groupAttr: member
            nameAttr: cn

    staticClients:
      - id: example-app
        redirectURIs:
          - "http://localhost:8000/callback"
        name: example-app
        secret: supersecret