apiVersion: apps/v1
kind: Deployment
metadata:
  name: own-track-proxy
  labels:
    app: own-track-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: own-track-proxy
  template:
    metadata:
      labels:
        app: own-track-proxy
    spec:
      containers:
        - name: own-track-proxy
          image: tracardi/airembr-owntrack-proxy:0.0.1
          imagePullPolicy: Always
          env:
            - name: LOGGING_LEVEL
              value: "debug"
            - name: AIREMBR_SOURCE_ID
              value: "4c09bf1a-4261-4c2e-b6dc-cc084d20b3d6"
            - name: AIREMBR_COLLECTOR_HOST
              value: "http://be-collector-api-svc.airembr.svc.cluster.local:4002"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: own-track-proxy-svc
spec:
  selector:
    app: own-track-proxy
  ports:
    - name: http
      port: 8000        # service port
      targetPort: 80    # container port
      protocol: TCP
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: own-track-proxy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: owntrack.airembr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: own-track-proxy-svc
                port:
                  number: 8000


