{{ if and .Values.gui.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: fe-gui-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "fe-rj-gui") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.gui.console.service.port }}
      targetPort: gui-port


{{ if .Values.gui.console.service.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: fe-gui-lb
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "fe-rj-gui") | nindent 6 }}
  ports:
    - name: http-{{ .Values.gui.console.service.port }}
      protocol: TCP
      port: {{ .Values.gui.console.service.port }}
      targetPort: gui-port
{{ end }}
{{ end }}