{{ if .Values.api.private.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: be-private-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.private.service.port }}
      targetPort: private-port

{{ if .Values.api.private.service.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: be-private-lb
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
  ports:
    - name: http-{{ .Values.api.private.service.port }}
      protocol: TCP
      port: {{ .Values.api.private.service.port }}
      targetPort: private-port
{{ end }}
{{ end }}