{{ if .Values.api.private.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: be-fa-private-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.private.service.port }}
      targetPort: private-port

{{ if .Values.digitalOcean.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: do-be-fa-private-lb
  {{ if .Values.digitalOcean.certId }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.digitalOcean.certId | quote }}
  {{ end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-private") | nindent 6 }}
  ports:
    - name: http-{{ .Values.api.private.service.port }}
      protocol: TCP
      port: {{ .Values.api.private.service.port }}
      targetPort: private-port
{{ if .Values.digitalOcean.certId }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: private-port
{{ end }}

{{ end }}

{{ end }}