{{ if .Values.api.public.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: be-public-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-public") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.public.service.port }}
      targetPort: be-fa-p-port

{{ if .Values.api.public.service.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: be-public-lb
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-public") | nindent 6 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.public.service.port }}
      targetPort: be-fa-p-port
{{ end }}
{{ end }}