{{ if .Values.api.public.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: be-public-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-public") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.public.service.port }}
      targetPort: be-fa-p-port

{{ if .Values.digitalOcean.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: be-public-lb
  {{ if .Values.digitalOcean.certId }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.digitalOcean.certId | quote }}
  {{ end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-public") | nindent 6 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.public.service.port }}
      targetPort: be-fa-p-port
    {{ if .Values.digitalOcean.certId }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: be-fa-p-port
    {{ end }}

{{ end }}
{{ end }}