{{ if and .Values.tms.docker.enabled (eq .Values.config.multiTenant.multi "yes") }}
apiVersion: v1
kind: Service
metadata:
  name: be-tms-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-tms") | nindent 6 }}
  ports:
    - name: http-{{ .Values.tms.docker.service.port }}
      protocol: TCP
      port: {{ .Values.tms.docker.service.port }}
      targetPort: tms-port

{{ if and  .Values.tms.docker.service.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: be-tms-lb
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "be-fa-tms") | nindent 6 }}
  ports:
    - name: http-{{ .Values.tms.docker.service.port }}
      protocol: TCP
      port: {{ .Values.tms.docker.service.port }}
      targetPort: tms-port
{{ end }}
{{ end }}