{{ if and .Values.tmsGui.docker.enabled .Values.tms.docker.enabled (eq .Values.config.multiTenant.multi "yes") }}
apiVersion: v1
kind: Service
metadata:
  name: fe-tms-gui-svc
spec:
  type: ClusterIP
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "fe-rj-tms-gui") | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.tmsGui.docker.service.port }}
      targetPort: tms-gui-port


{{ if and .Values.tmsGui.docker.service.loadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: fe-tms-gui-lb
spec:
  type: LoadBalancer
  selector:
    {{- include "tracardi.selectorLabels" (dict "ctx" . "component" "fe-rj-tms-gui") | nindent 6 }}
  ports:
    - name: http-{{ .Values.tmsGui.docker.service.port }}
      protocol: TCP
      port: {{ .Values.tmsGui.docker.service.port }}
      targetPort: tms-gui-port
{{ end }}
{{ end }}