apiVersion: v1
kind: Service
metadata:
  name: dgraph-alpha-lb
  namespace: dgraph
spec:
  type: LoadBalancer
  selector:
    app: dgraph
    component: alpha
    release: dgraph
  ports:
    - name: http
      port: 8888          # external HTTP port
      targetPort: 8080    # internal pod HTTP port
    - name: grpc
      port: 9088          # external gRPC port
      targetPort: 9080    # internal pod gRPC port

---
apiVersion: v1
kind: Service
metadata:
  name: dgraph-ratel-lb
  namespace: dgraph

spec:
  type: LoadBalancer
  selector:
    app: dgraph
    component: ratel
    release: dgraph
  ports:
    - name: http
      port: 8081        # external port
      targetPort: 8000 # internal pod port
