{{ if and .Values.secrets.dockerHub .Values.job.timer.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-timer
spec:
  schedule: {{ .Values.job.timer.config.cron | quote }}
  concurrencyPolicy: Forbid  # Prevent overlapping jobs
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.secrets.dockerHub | quote }}
          containers:
            - name: job-timer
              image: {{ .Values.job.timer.image.repository }}:{{ .Values.job.timer.image.tag }}
              imagePullPolicy: {{ .Values.job.timer.image.pullPolicy }}
              env:
              {{- include "tracardi.env" (dict "ctx" .) | nindent 14 }}
              - name: LOGGING_LEVEL
                value: {{ .Values.job.timer.config.loggingLevel | quote }}
          restartPolicy: Never
{{ end }}