master:
  persistence:
    size: 2Gi
    storageClass: "local-path"
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
replica:
  persistence:
    size: 5Gi
    storageClass: "local-path"
  replicaCount: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi